### ISSUE TITLE
Delete README.old.MD

### ISSUE THREAD

**Issue by sathp** [CS196Illinois/Fluid-Sensor#1]
This was the first README file we initialized.

**Comment by Lathie** [comment]
Procedure:

- Clone the repo if you haven't already (git clone <url>)
- Otherwise `git pull`
- `git checkout -b <new branch name>`
- Implement the changes
- `git add <changes>`
- `git commit -m "<commit message>"`
- `git push origin <new branch name>`
- On Github, compare and pull request your branch with master
- Post the PR link to messenger and I'll look at it
