### ISSUE TITLE
Change Background Color to Reflect App Color Hues

### ISSUE THREAD

**Issue by sathp** [CS196Illinois/Fluid-Sensor#3]
Find the hex codes of the app's pre-determined color hues and change App.js to reflect this.

**Comment by Lathie** [comment]
Procedure:

- Clone the repo if you haven't already (git clone <url>)
- Otherwise `git pull`
- `git checkout -b <new branch name>`
- Implement the changes
- `git add <changes>`
- `git commit -m "<commit message>"`
- `git push origin <new branch name>`
- On Github, compare and pull request your branch with master
- Let someone know!
